config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root "products#index"

  resources :cards, only: [:new, :show, :destroy] do
    member do
      post 'pay', to: 'cards#pay'
    end
  end
  resources :purchase, only: :show do
    member do
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end

  resources :users, only: :show do
    collection do
      get 'card'
    end
  end

  resources :products do
    collection do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'imageEdit'
      patch 'imageUpdate'
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PHONE = /\A\d{10}$|^\d{11}\z/
  VALID_KATAKANA = /\A[\p{katakana}\p{blank}ー－]+\z/

  validates :family_name, :first_name, :birthday, :nickname, :encrypted_password, presence: true
  validates :profile, presence: true, allow_blank: true
  validates :icon, presence: true, allow_blank: true
  validates :email, format: {with: VALID_EMAIL}, allow_blank: true
  validates :email, presence: true
  # validates :email, {presence: true, format: { with: VALID_EMAIL }, uniqueness: { case_sensitive: false }}
  validates :phone, {presence: true, format: { with: VALID_PHONE }, uniqueness: { case_sensitive: false }}
  validates :family_name_kana, presence: true, format: { with: VALID_KATAKANA, message: 'はカタカナで入力して下さい'}
  validates :first_name_kana, presence: true, format: { with: VALID_KATAKANA, message: 'はカタカナで入力して下さい'}

  has_many :products, dependent: :destroy
  has_one :address, dependent: :destroy
  has_one :card, dependent: :destroy

  mount_uploader :icon, ImageUploader
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def new
    @user = User.new
  end

  def create
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @address = @user.build_address
    render :new_address
  end

  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(address_params)
    unless @address.valid?
      flash.now[:alert] = @address.errors.full_messages
      render :new_address and return
    end
    @user.build_address(@address.attributes)
    @user.save
    session["devise.regist_data"]["user"].clear
    sign_in(:user, @user)
  end

  protected

  def address_params
    params.require(:address).permit(:postal_code, :prefecture_id, :city, :block, :apartment)
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end
  

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def card
    if @card = Card.find_by(user_id: current_user.id)
      # Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_SECRET_KEY]
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  private
  def address_params
    params.require(:address).permit(:postal_code, :prefecture_id, :city, :block, :apartment)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/card.html.haml
= render './header'

.wrapper
  .LinkList
    .LinkList__main
      = link_to user_path(current_user), class: 'LinkList__main--list' do
        マイページ
        %span.fas.fa-greater-than.greater
      %p.LinkList__main--list
        お知らせ
        %span.fas.fa-greater-than.greater
      %p.LinkList__main--list 
        ニュース
        %span.fas.fa-greater-than.greater
      = link_to new_product_path, class: 'LinkList__main--list' do
        出品する
        %span.fas.fa-greater-than.greater
      %p.LinkList__main--list 
        出品した商品
        %span.fas.fa-greater-than.greater
      %p.LinkList__main--list 
        購入した商品
        %span.fas.fa-greater-than.greater
      %p.LinkList__main--list 
        ガイド
        %span.fas.fa-greater-than.greater
      %p.LinkList__main--list 
        お問い合わせ
        %span.fas.fa-greater-than.greater
    .LinkList__config
      %h3.LinkList__config--top 設定
      %p.LinkList__config--list 
        プロフィール
        %span.fas.fa-greater-than.greater
      %p.LinkList__config--list 
        発送元、お届け先
        %span.fas.fa-greater-than.greater
      = link_to card_users_path, class: 'LinkList__config--list listActive' do
        支払い方法
        %span.fas.fa-greater-than.greater
      = link_to destroy_user_session_path, method: :delete, class: 'LinkList__config--list' do
        ログアウト
        %span.fas.fa-greater-than.greater
  .Payment
    %h3.Payment--top 支払い方法
    .Payment__add
      %h3.Payment__add--top クレジットカード一覧
      - if @card.present?
        .Payment__add__data
          .Payment__add__data--info
            = "**** **** **** " + @default_card_information.last4
            %br
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
          .Payment__add__data--btn
            = link_to "削除", card_path(@card), method: :delete, class: "delete-btn"
      - else
        = link_to new_card_path, class: 'Payment__add--btn' do
          %span.fas.fa-credit-card.Payment__add--pay
          クレジットカードを追加する
      .Payment__add--border

= render './footer'

app/views/users/show.html.haml
= render './header'

.wrapper
  .LinkList
    .LinkList__main
      = link_to user_path(current_user), class: 'LinkList__main--list listActive' do
        マイページ
        %span.fas.fa-greater-than.greater
      %p.LinkList__main--list
        お知らせ
        %span.fas.fa-greater-than.greater
      %p.LinkList__main--list 
        ニュース
        %span.fas.fa-greater-than.greater
      = link_to new_product_path, class: 'LinkList__main--list' do
        出品する
        %span.fas.fa-greater-than.greater
      %p.LinkList__main--list 
        出品した商品
        %span.fas.fa-greater-than.greater
      %p.LinkList__main--list 
        購入した商品
        %span.fas.fa-greater-than.greater
      %p.LinkList__main--list 
        ガイド
        %span.fas.fa-greater-than.greater
      %p.LinkList__main--list 
        お問い合わせ
        %span.fas.fa-greater-than.greater
    .LinkList__config
      %h3.LinkList__config--top 設定
      %p.LinkList__config--list 
        プロフィール
        %span.fas.fa-greater-than.greater
      %p.LinkList__config--list 
        発送元、お届け先
        %span.fas.fa-greater-than.greater
      = link_to card_users_path, class: 'LinkList__config--list' do
        支払い方法
        %span.fas.fa-greater-than.greater
      = link_to destroy_user_session_path, method: :delete, class: 'LinkList__config--list' do
        ログアウト
        %span.fas.fa-greater-than.greater
  .UserData
    .UserData__data
      .UserData__data--icon 
      %h3 #{current_user.nickname}
    .UserData__info
      .UserData__info__notice.noticeActive
        %h3 お知らせ
      .UserData__info__notice
        %h3 ニュース
    .UserData__contents1#notice
    .UserData__contents1#news
    .UserData__bought
      %h3 購入した商品
    .UserData__contents2
      .noData
      %h3.noDataText 購入した商品が存在しません

= render './footer'