config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root "products#index"

  resources :cards, only: [:new, :show, :destroy] do
    member do
      post 'pay', to: 'cards#pay'
    end
  end
  resources :purchase, only: :show do
    member do
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end

  resources :users, only: :show do
    collection do
      get 'card'
    end
  end

  resources :products do
    collection do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'imageEdit'
      patch 'imageUpdate'
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user

  validates :user_id, :customer_id, :card_id, presence: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp"
  
  def new
    card = Card.where(user_id: current_user.id)
  end

  def pay
    # Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_SECRET_KEY]
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: :new
    else
      customer = Payjp::Customer.create(
        card: params['payjp-token'],
        metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to card_users_path
      else
        render :pay
      end
    end
  end

  def destroy
    card = Card.where(user_id: current_user.id).first
    if card.present?
      # Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_SECRET_KEY]
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
    redirect_to action: :new
  end

  def show
    card = Card.where(user_id: current_user.id).first
    # Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_SECRET_KEY]
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    customer = Payjp::Customer.retrieve(card.customer_id)
    @default_card_information = customer.cards.retrieve(card.card_id)
  end
end

app/views/cards/new.html.haml
= render './header'

.wrapper
  .LinkList
    .LinkList__main
      = link_to user_path(current_user), class: 'LinkList__main--list' do
        マイページ
        %span.fas.fa-greater-than.greater
      %p.LinkList__main--list
        お知らせ
        %span.fas.fa-greater-than.greater
      %p.LinkList__main--list 
        ニュース
        %span.fas.fa-greater-than.greater
      = link_to new_product_path, class: 'LinkList__main--list' do
        出品する
        %span.fas.fa-greater-than.greater
      %p.LinkList__main--list 
        出品した商品
        %span.fas.fa-greater-than.greater
      %p.LinkList__main--list 
        購入した商品
        %span.fas.fa-greater-than.greater
      %p.LinkList__main--list 
        ガイド
        %span.fas.fa-greater-than.greater
      %p.LinkList__main--list 
        お問い合わせ
        %span.fas.fa-greater-than.greater
    .LinkList__config
      %h3.LinkList__config--top 設定
      %p.LinkList__config--list 
        プロフィール
        %span.fas.fa-greater-than.greater
      %p.LinkList__config--list 
        発送元、お届け先
        %span.fas.fa-greater-than.greater
      = link_to card_users_path, class: 'LinkList__config--list leftActive' do
        支払い方法
        %span.fas.fa-greater-than.greater
      = link_to destroy_user_session_path, method: :delete, class: 'LinkList__config--list' do
        ログアウト
        %span.fas.fa-greater-than.greater
  .Payment
    %h3.Payment--top クレジットカード情報入力
    = form_tag(pay_card_path(current_user.id), id: 'charge-form', class: 'Payment__card', name: "inputForm") do
      .Payment__number
        %h3.Payment__number--top
          カード番号
          %span.must 必須
        = text_field_tag "number", "", class: "number Payment__card--form", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
        %ul.signup-card-list
          %li
            = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/visa.svg?238737266",width:"49px",height:"20px"
          %li
            = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?238737266",width:"34px",height:"20px"
          %li
            = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?238737266",width:"30px",height:"20px"
          %li
            = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?238737266",width:"32px",height:"20px"
          %li
            = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?238737266",width:"21px",height:"20px"
          %li
            = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?238737266",width:"32px",height:"20px"
          %li
            = image_tag "https://www-mercari-jp.akamaized.net/assets/img/card/discover.svg?238737266",width:"32px",height:"20px"
      .Payment__limit
        %h3.Payment__limit--top
          有効期限
          %span.must 必須
        %select#exp_month.Payment__card--formhalf{name: "exp_month", type: "text"}
          %option{value: ""} --
          %option{value: "1"}01
          %option{value: "2"}02
          %option{value: "3"}03
          %option{value: "4"}04
          %option{value: "5"}05
          %option{value: "6"}06
          %option{value: "7"}07
          %option{value: "8"}08
          %option{value: "9"}09
          %option{value: "10"}10
          %option{value: "11"}11
          %option{value: "12"}12
        %span 月
        %select#exp_year.Payment__card--formhalf{name: "exp_year", type: "text"}
          %option{value: ""} --
          %option{value: "2020"}20
          %option{value: "2021"}21
          %option{value: "2022"}22
          %option{value: "2023"}23
          %option{value: "2024"}24
          %option{value: "2025"}25
          %option{value: "2026"}26
          %option{value: "2027"}27
          %option{value: "2028"}28
          %option{value: "2029"}29
        %span 年
      .Payment__cord
        %h3.Payment__cord--top
          セキュリティコード
          %span.must 必須
        = text_field_tag "cvc", "", class: "cvc Payment__card--form", placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4", id: "cvc"
      #card_token
      = submit_tag "追加する", id: "token_submit", class: 'Payment__card--btn'

= render './footer'