config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root "products#index"

  resources :cards, only: [:new, :show, :destroy] do
    member do
      post 'pay', to: 'cards#pay'
    end
  end
  resources :purchase, only: :show do
    member do
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end

  resources :users, only: :show do
    collection do
      get 'card'
    end
  end

  resources :products do
    collection do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'imageEdit'
      patch 'imageUpdate'
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  
  belongs_to :category
  belongs_to :user
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  validates :name, :detail, :fee, :condition, :day, :user_id, :prefecture_id, :shipping, presence: true
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}

  enum brand_id: {"シャネル": 0, 
                  "グッチ": 1, 
                  "プラダ": 2, 
                  "エルメス": 3, 
                  "バレンシアガ": 4, 
                  "フェンディ": 5, 
                  "ボッテガ・ヴェネタ": 6, 
                  "ヴァレンチノ": 7, 
                  "サン・ローラン": 8, 
                  "アルマーニ": 9 }

  enum size: {"XXS以下": 0, 
              "XS(SS)": 1, 
              "S": 2, 
              "M": 3, 
              "L": 4, 
              "XL(LL)": 5, 
              "2XL(3L)": 6, 
              "3XL(4L)": 7, 
              "4XL(5L)以上": 8, 
              "FREESIZE": 9 }

  enum condition: { "新品・未使用": 1, 
                    "未使用に近い": 2,
                    "目立った傷や汚れなし":3,
                    "やや傷や汚れあり":4,
                    "傷や汚れあり":5,
                    "全体的に状態が悪い":6 }

  enum fee: { "送料込み（出品者負担)":1, 
              "送料込み（出品者負担）":2, 
              "着払い（購入者負担）":3, 
              "着払い（購入者負担）":4 }

  enum day: { "1~2日で発送":1,  
              "2〜3日で発送":2,
              "4〜7日で発送":3 }

  enum shipping: {"メルカリ便":1, 
                  "ヤマト":2, 
                  "レターパック":3 }

  enum prefecture_id:{
    "北海道":1,     "青森県":2,     "岩手県":3,
    "宮城県":4,     "秋田県":5,     "山形県":6,
    "福島県":7,     "茨城県":8,     "栃木県":9,
    "群馬県":10,    "埼玉県":11,    "千葉県":12,
    "東京都":13,    "神奈川県":14,  "新潟県":15,
    "富山県":16,    "石川県":17,    "福井県":18,
    "山梨県":19,    "長野県":20,    "岐阜県":21,
    "静岡県":22,    "愛知県":23,    "三重県":24,
    "滋賀県":25,    "京都府":26,    "大阪府":27,
    "兵庫県":28,    "奈良県":29,    "和歌山県":30,
    "鳥取県":31,    "島根県":32,    "岡山県":33,
    "広島県":34,    "山口県":35,    "徳島県":36,
    "香川県":37,    "愛媛県":38,    "高知県":39,
    "福岡県":40,    "佐賀県":41,    "長崎県":42,
    "熊本県":43,    "大分県":44,    "宮崎県":45,
    "鹿児島県":46,  "沖縄県":47
  }

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # before_action :move_to_index, except: [:index, :show]
  before_action :ensure_current_user, only: [:edit, :update, :destroy]
  before_action :set_product, only: [:imageEdit, :imageUpdate, :edit, :update, :destroy, :show]

  def index
    @products = Product.includes(:images).order('created_at DESC')
    @items = Product.where(buyer_id: nil).includes(:images).order('created_at DESC')
    @brand = Product.where(buyer_id: nil, brand_id: 0).includes(:images).order('created_at DESC')
  end

  def show
    @grandchild = Category.find(@product.category_id)
    @child = @grandchild.parent
    @parent = @child.parent
    @images = @product.images
  end
  
  def new
    if user_signed_in?
      @product = Product.new
      @product.images.new
      @category = Category.all.order("id ASC").limit(13)
      @length = 0
    else
      redirect_to new_user_session_path
    end
  end
  
  def create
    @product = Product.new(product_params)
    @category = Category.all.order("id ASC").limit(13)
    if @product.images.present?
      if @product.price >= 300 && @product.price <= 9999999
        @product.save
        redirect_to root_path
      else 
        flash[:alert] = '価格は300円から9999999円までです'
        render :new
      end
    else
      flash[:alert] = '画像を選択してください'
      redirect_to new_product_path
    end
  end

  def imageEdit
    @length = @product.images.length
    @checks = []
  end

  def imageUpdate
    boxcheck = params[:boxcheck]
    if @product.update(product_params)
      redirect_to edit_product_path(params[:id], boxcheck: boxcheck), notice: '更新されました'
    else
      render :imageEdit
    end
  end

  def edit
    @category = Category.all.order("id ASC").limit(13)
    @length = @product.images.length
    @boxcheck = params[:boxcheck]
  end
    
  def category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find(params[:productcategory]).children 
  end

 # 子カテゴリーが選択された後に動くアクション
  def category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    # @category_grandchildren = Category.find("#{params[:child_id]}").children
    @category_grandchildren = Category.find(params[:productcategory]).children
  end

  def update
    if @product.update(product_params)
      redirect_to product_path(params[:id]), notice: '更新されました'
    else
      render :edit
    end
  end
  
  def destroy
    if @product.destroy
      redirect_to products_path, notice: '削除されました'
    else 
      render :index
    end
  end

  private
  def ensure_current_user
    product = Product.find(params[:id])
    if product.user_id != current_user.id
      flash[:notice] = "no authorization"
      redirect_to action: :index
    end
  end

  def product_params
    params.require(:product).permit(:name, :detail, :condition, :size, :day, :shipping, :fee, :category_id, :parent_name, :child_id, :brand_id, :prefecture_id, :buyer_id, :price, images_attributes: [:src, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def set_product
    @product = Product.find(params[:id])
  end
  
  # def move_to_index
  #   redirecto_to action: :index unless user_signed_in?
  # end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_button.html.haml
= link_to new_product_path do
  .Exhibition
    %span.Exhibition__text
      出品
    .Exhibition__icon
      = image_tag 'icon_camera.png', width: '60%'

app/views/products/_form.html.haml
#container
  = render partial: './simpleHeader'
  #main
    = form_with model: @product, local: true do |f|
      - if @product.persisted?
        .display-none
          %p#boxcheck #{@boxcheck}
          = f.fields_for :images do |i|
            = i.check_box :_destroy, data:{ index: i.index }, class: 'hidden-destroy'
      - unless @product.persisted?
        #images
          .notifications
            - flash.each do |key, value|
              = content_tag(:div, value, class: key)
          %b 出品画像
          %span （ドラッグアンドドロップで画像を追加できます。）
          #image-box-1
            .item-num-0#image-box__container{ data: { index: @length } }
              = f.fields_for :images do |i|
                .input-area
                  = i.file_field :image, type: 'file', name: "product[images_attributes][][src]", value:"", style: "display:none", id:"img-file"
                  %label{for: "img-file"}
                    %i.fas.fa-camera
      #description
        %b 商品名
        %span.necessary 必須
        = f.text_field :name, required: true
        %br/
        %b 商品の説明
        %span.necessary 必須
        = f.text_area :detail, required: true
        %br/
      #about
        .error-message.error-message-hidden
          カテゴリーを選択してください
        %b カテゴリー
        %span.necessary 必須
        - if @product.persisted?
          .listing-select-wrapper--edit
            .listing-select-wrapper--edit__parent
              = f.collection_select :category_id, Category.roots, :id, :name ,{prompt: "選択してください", selected:  @product.category.parent.parent_id}, {class: 'listing-select-wrapper--edit__parent--select', id: 'parent_category_edit', name: "" }
            .listing-select-wrapper--edit__child
              = f.collection_select :category_id, @product.category.parent.parent.children, :id, :name ,{prompt: "選択してください", selected: @product.category.parent_id}, {class: 'listing-select-wrapper--edit__child--select', id: 'child_category_edit', name: "" }
            .listing-select-wrapper--edit__grandchild
              = f.collection_select :category_id,@product.category.parent.children, :id, :name ,{prompt: "選択してください", selected: @product.category.id}, {class: 'listing-select-wrapper--edit__grandchild--select', id: 'grandchild_category_edit', name: "product[category_id]" }
        - else
          = f.collection_select :category, @category, :id, :name, { prompt: "選択してください" }, { class: "category_select-box", id: "category_select",required: true }
          .product_select-children
        %br/
        %b ブランド
        %span.option 任意
        = f.select :brand_id, Product.brand_ids.keys, { prompt: "選択してください" }, class: 'formBox'
        %br/
        %b 商品の状態
        %span.necessary 必須
        = f.select :condition, Product.conditions.keys, { prompt: "選択してください" }, required: true
        %br/
        %b サイズ
        %span.option 任意
        = f.select :size, Product.sizes.keys, { prompt: "選択してください" }, class: 'formBox'
        %br/
      #shipping
        %b 配送料の負担
        %span.necessary 必須
        = f.select :fee, Product.fees.keys, { prompt: "選択してください" }, required: true
        %br/
        %b 配送元の地域
        %span.necessary 必須
        = f.select :prefecture_id, Product.prefecture_ids.keys, { prompt: "選択してください" }, required: true
        %br/
        %b 配送までの日数
        %span.necessary 必須
        = f.select :day, Product.days.keys, { prompt: "選択してください" }, required: true
        %br/
        %b 配送方法
        %span.necessary 必須
        = f.select :shipping, Product.shippings.keys, { prompt: "選択してください" }, required: true
        %br/
      #pricing
        .left
          %b 販売価格
          %span.necessary 必須
        .right
          %span ¥
          = f.number_field :price, required: true, class: 'formBox'
      #btns
        = f.submit "出品する", class: 'btn1'
        = link_to("下書きに保存", "#", class: "btn2")
        = link_to("もどる", root_path, class: "background")

    .warning
      禁止された
      %span.certification 行為
      および
      %span.certification 出品物
      を必ずご確認ください。
      %span.certification 偽ブランド品
      や
      %span.certification 盗品物
      などの販売は犯罪であり、
      %br
      法律により処罰される可能性があります。また、出品をもちまして
      %span.certification 加盟店規約
      に同意したことになります。

= render partial: './simpleFooter'

app/views/products/_main.html.haml
.TopMain
  .Top
    .Content
      %h2.Content__title
        %br 人生を変えるフリマアプリ
      
      %p.Content__text
        FURIMAはだれでもかんたんに出品・購入ができる
        %br
        フリマアプリです
      .Button
        .Button__apple
          = image_tag("apple.png", width: 180)
        .Button__google
          = image_tag("google.png", width: 180)
  .Middle
    %h2.Middle__comment
      FURIMAが選ばれる3つの理由
      .Line
    %ul.Lists
      %li.List
        .List__image
          = image_tag 'pict-reason-01.jpg', width: '100%'
          %span.List__number 1
        %h3.List__text
          %span.aoiro
            3分
          ですぐに出品
        %p.List__comment
          スマホに入力するだけで簡単に出品できる！
      %li.List
        .List__image
          = image_tag 'pict-reason-02.jpg', width: '100%'
          %span.List__number 2
        %h3.List__text
          %span.aoiro
            シンプル
          で使いやすい
        %p.List__comment
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.List
        .List__image
          = image_tag 'pict-reason-03.jpg', width: '100%'
          %span.List__number 3
        %h3.List__text
          手数料
          %span.aoiro
            業界最安
        %p.List__comment
          最大3％でお得に購入＆出品
  .Center
    .Center__textBox
      %h2.Center__title
        会員数日本一
      %p.Center__text
        FURIMAは、フリマアプリで最も人気
        %br
        出品・購入回数も業界最多です！
        %br
        ほしかったあの商品に出会えるかもしれません。
        %br
        .Button
          .Button__apple
            = image_tag("apple.png", width: 180)
          .Button__google
            = image_tag("google.png", width: 180)
  .Feature
    %h2.Feature__Head
      FURIMAの特徴
      .Line
    .Feature__Icons
      .Feature__Icon
        .Feature__Icon--image
          = image_tag 'icon-01.png', width: '70%'
        %h3.Feature__Icon--title
          簡単に売り買いできる
        %p.Feature__Icon--text
          スマホ一つで、いつでもどこでも簡単に出品・購入が可能
      .Feature__Icon
        .Feature__Icon--image
          = image_tag 'icon-03.png', width: '70%'
        %h3.Feature__Icon--title
          売上金は即日振込みに対応
        %p.Feature__Icon--text
          午前9時までに振込を依頼していただければ、翌日に指定口座に入金いたします！
      .Feature__Icon
        .Feature__Icon--image
          = image_tag 'icon-04.png', width: '70%'
        %h3.Feature__Icon--title
          様々なお支払いに対応
        %p.Feature__Icon--text
          お支払いはクレジットカードだけではなく、ポイントや売上金など多彩な方法があります。
  .Pickup
    %h2.Pickup__head
      ピックアップカテゴリー
    .Product
      .Product__title
        .title
          新規投稿商品
      .Product__lists
        - @items.each_with_index do |product, i|
          - if i < 4
            .Product__list
              = link_to product_path(product) do
                .Product__image
                  = image_tag product.images.first.src.url, height: '150px', width: '220px'
                .Product__date
                  .Product__date--name
                    #{product.name}
                  .Product__date--price
                    #{product.price}円
                    %p
                      (税込)
  .Pickup
    %h2.Pickup__head
      ピックアップブランド
    .Product
      .Product__title
        .title
          シャネル
      .Product__lists
        - @brand.each_with_index do |product, i|
          - if i < 4
            .Product__list
              = link_to product_path(product) do
                .Product__image
                  = image_tag product.images.first.src.url, height: '150px', width: '220px'
                .Product__date
                  .Product__date--name
                    #{product.name}
                  .Product__date--price
                    #{product.price}円
                    %p
                      (税込)
= render partial: './footer'

app/views/products/edit.html.haml
= render partial: 'form'

app/views/products/imageEdit.html.haml
#container
  = render partial: './simpleHeader'
  #main
    = form_with url: imageUpdate_product_path(@product.id, boxcheck: @checks), method: :patch, local: true, id: 'form1' do |f|
      #images
        .notifications
          - flash.each do |key, value|
            = content_tag(:div, value, class: key)
        %b 出品画像
        %span （ドラッグアンドドロップで画像を追加できます。）
        #image-box-1
          - @product.images.each_with_index do |image, i|
            .item-image{ data: { index: "#{i}" } }
              .item-image__content
                .item-image__content--icon
                  = image_tag("#{image.src.url}", width: 120, height: 120)
              .item-image__operetion
                .item-image__operetion--delete
                  削除
            = f.fields_for :images do |i|
              = i.check_box :_destroy, data:{ index: i.index }, class: 'hidden-destroy'
          .item-num-0#image-box__container{ data: { index: @length } }
            = f.fields_for :images do |i|
              .input-area
                = i.file_field :image, type: 'file', name: "product[images_attributes][][src]", value:"", style: "display:none", id:"img-file"
          %label{for: "img-file"}
            %i.fas.fa-camera.camera
      #btns 
        = f.submit '出品画像を更新する', class: "btn1"
      #about.hidden-destroy
        .error-message.error-message-hidden
          カテゴリーを選択してください
        %b カテゴリー
        %span.necessary 必須
        .listing-select-wrapper--edit
          .listing-select-wrapper--edit__parent
            = f.collection_select :category_id, Category.roots, :id, :name ,{prompt: "選択してください", selected:  @product.category.parent.parent_id}, {class: 'listing-select-wrapper--edit__parent--select', id: 'parent_category_edit', name: "" }
          .listing-select-wrapper--edit__child
            = f.collection_select :category_id, @product.category.parent.parent.children, :id, :name ,{prompt: "選択してください", selected: @product.category.parent_id}, {class: 'listing-select-wrapper--edit__child--select', id: 'child_category_edit', name: "" }
          .listing-select-wrapper--edit__grandchild
            = f.collection_select :category_id,@product.category.parent.children, :id, :name ,{prompt: "選択してください", selected: @product.category.id}, {class: 'listing-select-wrapper--edit__grandchild--select', id: 'grandchild_category_edit', name: "product[category_id]" }
        
= render partial: './simpleFooter'

app/views/products/index.html.haml
= render partial: './header'
= render partial: 'main'
= render partial: 'button'

app/views/products/new.html.haml
= render partial: 'form'

app/views/products/show.html.haml
= render partial: './simpleHeader'

.ProductShow
  .ProductShow__container
    .ProductShow__container--one
      %h1.ProductShow__title
        = @product.name
      .ProductShow__content
        .ProductShow__imageBox          
          = image_tag("#{@product.images[0].src.url}", width: "300", height: "300", class: 'ProductShow__imageTop')
          .ProductShow__images
            = image_tag("#{@product.images[0].src.url}", width:"60", height:"60", class: 'ProductShow__images--image active')
            - @images[1..-1].each do |image|
              = image_tag("#{image.src.url}", width:"60", height:"60", class: 'ProductShow__images--image')
        %table.ProductShow__tableBox
          %tbody
            %tr
              %th.word
                出品者
              %td.info__sky
                = @product.user.nickname
                %br
            %tr
              %th.word
                カテゴリー
              %td.info__sky
                = @parent.name
                %br
                >
                = @child.name
                %br
                >
                = @grandchild.name
            %tr
              %th.word
                ブランド
              %td.info__sky
                = @product.brand_id
            %tr
              %th.word
                商品サイズ
              %td.info
                = @product.size
            %tr
              %th.word
                商品の状態
              %td.info
                = @product.condition
            %tr
              %th.word
                配送料負担
              %td.info
                = @product.fee
            %tr
              %th.word
                発送方法
              %td.info
                = @product.shipping
            %tr
              %th.word
                配送元地域
              %td.info
                = @product.prefecture_id
            %tr
              %th.word
                発送日の目安
              %td.info
                = @product.day
            %tr
      .ProductShow__price
        =  "¥#{@product.price}"
        %span.tax (税込み)
        %span.fee 送料込み
      .ProductShow__list
        - if @product.buyer_id
          = link_to '売り切れました', products_path
        - unless user_signed_in? && current_user.id == @product.user_id
          %div#buy-button
            = link_to "購入画面に進む", purchase_path(@product.id),{class: 'buybtn'}
        %p.exhibitor-comment
          = @product.detail
        %br
        %p.safety あんしん・あんぜんへの取り組み
    - if user_signed_in? && current_user.id == @product.user_id
      #buy-buttons
        = link_to '商品の編集', imageEdit_product_path(@product.id), class: "ProductShow__container--edit"
        %p or
        = link_to '出品を一旦停止する', "#", class: "halt"
        = link_to 'この商品を削除する', product_path(@product.id), method: :delete, class: "delete"
    - if user_signed_in?
      .ProductShow__commentbox
        %form.comment{:action => "", :method => "get"}
          %p.attention
            相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        %textarea.comment__text
        %button.comment__btn
          %span
            コメントする

= render partial: './simpleFooter'